company:
  name: "My Company"
  start_date: "2024-01-01"  # YYYY-MM-DD format - your company start date
  email_list: "team@mycompany.com"  # Email address to send journal entries to

journal:
  entries_dir: "journal_entries"  # Directory to store journal entries

email:
  from_address: "your-email@gmail.com"  # Your Gmail address
  smtp_server: "smtp.gmail.com"
  smtp_port: 587